services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jk-receipt-app
    restart: always
    ports:
      - "3011:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - DATABASE_URL=postgres://jejaku:jejaku_password@db:5432/jejaku_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: jk-receipt-db
    restart: always
    environment:
      POSTGRES_USER: jejaku
      POSTGRES_PASSWORD: jejaku_password
      POSTGRES_DB: jejaku_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
